routes/web.php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('main');

/*
 *	Rutas de Importacion y de Moodle
 */
Route::group(['prefix' => 'cron'], function () {
  Route::get('import', 'CronAutomatico\CronController@mainFunction');

  Route::post('manual_import', 'CronAutomatico\CronController@manualImport');
  Route::get('process_import/{filename}', 'CronAutomatico\CronController@processImport');
});

Route::post('cambiar-contrasena/{id_user}', 'ClimaOrganizacional\UsersController@cambiar_contrasena');
Route::get('cambiar-contrasena/{id_user}', 'ClimaOrganizacional\UsersController@cambiar_contrasena');

/**
 *  ================ Announcement Routes ================ 
 */
Route::resource('announcements', 'Announcement\AnnouncementController');
Route::resource('announcement_types', 'Announcement\AnnouncementTypeController');
Route::resource('announcement_categories','Announcement\AnnouncementCategoryController');
Route::resource('views', 'Announcement\ViewController');
Route::resource('announcement_forms', 'Announcement\AnnouncementFormController');
Route::resource('announcement_types_per_view', 'Announcement\AnnouncementTypePerViewController');

Route::get('example', 'Announcement\AnnouncementController@example');
Route::post('announcements/{announcement}/activate', 'Announcement\AnnouncementController@activate');

Route::get('organigrama', 'HomeController@organigrama');
Route::get('organigrama-puestos', 'HomeController@organigramaPuestos');
Route::get('cumpleaños', 'BirthdayController@index')->name('cumpleaños');
Route::get('filosofia', 'HomeController@filosofia');

/**
 *  =============== /Announcement Routes ================
 */

 /**
 *   ================ Admin de Usuarios ================ 
 */
Route::resource('admin-de-usuarios','UserController');
Route::resource('admin-form','EmployeeFormController');
Route::get('user_analytics','UserController@analytics');
Route::post('get_user_analytics','UserController@getAnalyticsData');
Route::post('update_password', 'UserController@updatePassword');
Route::get('authMeWith/{user_email}', 'UserController@authMeWith');
Route::post('admin-de-usuarios/{id}/activate','UserController@activate')->name('activate-user');
Route::get('generar-contrato/{id}','UserController@generarContrato');
// Route::get('generate_users_random_passwords','UserController@generateUsersRandomPass');

Route::resource('direcciones','DirectionController');
Route::resource('departamentos','DepartmentController');
Route::resource('areas','AreaController');

Route::get('trashedDepartments/{id}','DepartmentController@getTrashed')->name('trashed-departments');
Route::get('trashedAreas/{id}','AreaController@trashedAreas')->name('trashed-areas');

Route::get('departments/{id}','PuestoController@departments')->name('departments');
Route::get('area/{id}','PuestoController@areas')->name('area');
Route::get('trashedJobs/{id}','PuestoController@trashedJobs')->name('trashed-jobs');
Route::get('jobpositions/{id}','PuestoController@jobpositions')->name('jobpositions');
Route::get('jobboss','PuestoController@jobboss')->name('jobboss');
Route::get('levels','PuestoController@levels')->name('levels');

Route::get('correo_de_bienvenida/{id?}', 'UserController@sendWelcomeMail')->middleware('permission:user_admin');
 /**
 *   =============== /Admin de Usuarios ================ 
 */


 
//*********************************************************************************
//rutas para la requisición de personal
//inicio
// Route::get('requisitions/{id}/autorizar', 'Requisitions\RequisitionController@autorizar');
// Route::post('rechazarRequi', 'Requisitions\RequisitionController@rechazar');

// Route::resource('requisitions', 'Requisitions\RequisitionController');
//fin
//*********************************************************************************

//*********************************************************************************
//rutas para vacntes de personal y todos los elemetos necesarios
//vacantes - reclutadores
//inicio
// Route::get('vacantes/showExt/{id}', 'Vacantes\VacantesController@showExt');
// Route::get('vacantes/administrar', 'Vacantes\VacantesController@administrar');
// Route::get('vacantes/reclutador', 'Vacantes\VacantesController@reclutador');
// Route::get('vacantes/recruiter/{id}', 'Vacantes\VacantesController@recruiter');
// Route::post('vacantes/addRecruiter', 'Vacantes\VacantesController@addRecruiter');
// Route::get('vacantes/{id}/closeVacancie', 'Vacantes\VacantesController@closeVacancie');
// Route::get('vacantes/closedVacancies', 'Vacantes\VacantesController@closedVacancies');

// Route::get('postulante/{id}/crear', 'Vacantes\PostulanteController@crear');
// Route::get('postulante_cerrada/{id}', 'Vacantes\PostulanteController@showClosed');
// Route::get('encuesta/{id}', 'Vacantes\PostulanteController@encuesta');

// Route::resources([
//   'vacantes' => 'Vacantes\VacantesController',
//   'reclutador' => 'Vacantes\ReclutadorController',
//   'postulante' => 'Vacantes\PostulanteController'
// ]);
 
//fin
//*********************************************************************************

//*********************************************************************************
//rutas para el perfil de personal
//inicio
Route::get('profile/{u}/{p}/{v}/consulta', 'Profile\ProfileController@consulta');
Route::get('profile/{p}/{v}/generar', 'Profile\ProfileController@generar');
Route::post('createBasica', 'Profile\ProfileController@createBasica');
Route::post('createComplementaria', 'Profile\ProfileController@createComplementaria');
Route::post('createRegistro', 'Profile\ProfileController@createRegistro');
Route::put('updateRegistro', 'Profile\ProfileController@updateRegistro');
Route::post('createSalud', 'Profile\ProfileController@createSalud');
Route::put('updateSalud', 'Profile\ProfileController@updateSalud');
Route::post('createBeneficiarios', 'Profile\ProfileController@createBeneficiarios');
Route::put('updateBeneficiarios', 'Profile\ProfileController@updateBeneficiarios');

Route::get('curriculum/{idVi?}', 'Profile\ProfileController@curriculum');
Route::get('profile/{id}/{idVi}/externo', 'Profile\ProfileController@externo');
Route::get('profile/{id}/showExternal', 'Profile\ProfileController@showExternal');
Route::get('listsprofile', 'Profile\ProfileController@listsprofile');

Route::resource('profile', 'Profile\ProfileController');
//fin
//*********************************************************************************

/********************************************************************************** */
//rutas para el listado dependiente de estados y municipios
//inicio ***************
Route::get('listStates/{id}', 'Entidades\EntidadesController@listadoMunicipios');
 
//fin

//rutas para el puestos de la empresa
//inicio ***************
Route::resource('jobPosition', 'JobPositionController');
Route::get('get_jobposition_data/{id?}', 'JobPositionController@getJobPositionData');
//Se agrega esta ruta, ya que es una consulta a la tabla puestos y obtener
//el beneficio del puesto de la persona logueada
Route::get('beneficios', 'JobPositionController@beneficios');
//fin



//*************************************************************************
//rutas para el modulo de Vacaciones
//inicio ***************
// Route::group(['prefix' => 'common', 'as' => 'common.'], function () {
//     Route::get('balances', 'EmployeeController@balances')->name('balances');
//     Route::get('inactive', 'Vacations\PleaController@getInactive')->name('plea.inactive');
//     Route::resource('plea', 'Vacations\PleaController');
// });

// Route::group(['prefix' => 'super', 'as' => 'super.'], function () {
//     Route::get('approve/{request}', 'Vacations\SuperController@approve')->name('approve');
//     Route::get('eventstable', 'Vacations\EventsController@table');
//     Route::post('requests', 'Vacations\SuperController@requests')->name('requests');
//     Route::post('incidents', 'Vacations\SuperController@incidents');
//     Route::post('incidents/{id}', 'Vacations\SuperController@update');
//     Route::resource('events', 'Vacations\EventsController');
//     Route::get('userstable', 'UsersController@table');
//     Route::get('users/{id}/add', 'UsersController@addBenefit');
//     Route::post('users/{id}/add', 'UsersController@setBenefit');
//     Route::resource('users', 'UsersController');
//     Route::get('excel/requests', 'Export\ExcelController@requests');
//     Route::get('excel/incidents', 'Export\ExcelController@incidents');
//     Route::get('view/incidents', 'Vacations\AdminController@incidents');
//     Route::get('view/requests', 'Vacations\AdminController@requests')->name('view.requests');
//     Route::get('tableincidents', 'Vacations\AdminController@tableIncidents');
//     Route::post('tableincidents', 'Vacations\AdminController@tableIncidents');
//     Route::get('tablerequests', 'Vacations\AdminController@tableRequests');
//     Route::post('tablerequests', 'Vacations\AdminController@tableRequests'); 
// });
 
//fin

/* Nom035 */
Route::group(['prefix' => 'nom035'], function () {
    Route::get('informe', 'Nom035\EvaluadosController@informe');
    Route::get('reporte-grafico', 'Nom035\EvaluadosController@reporte_grafico');
    Route::get('reportes', 'Nom035\ReporteGraficoController@index');
    Route::post('reportes', 'Nom035\ReporteGraficoController@post')->name('reports.post');
    Route::get('reporte_tabla', 'Nom035\ReporteGraficoController@reporte_tabla');
    Route::post('reporte_tabla', 'Nom035\ReporteGraficoController@post_tabla')->name('reports.post_tabla');

app/Models/JobPosition.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Employee;

class JobPosition extends Model
{
    use SoftDeletes;
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'job_positions';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'description',
        'file',
        'experience',
        'knowledge',
        'comments',
        'enterprise',
        'benefits',
        'job_position_level_id',
        'job_position_boss_id',
        'area_id'];

    public function scopeBossTop($query){
        return $query->whereNull('job_position_boss_id');
    }

    /*public function area()
    {
        return $this->belongsTo(Area::class, 'area_id', 'id');
    }*/

    public function department()
    {
        return $this->belongsTo(Department::class, 'department_id', 'id');
    }

    public function area()
    {
        return $this->belongsTo(Area::class, 'area_id', 'id');
    }

    public function level()
    {
        return $this->belongsTo(JobPositionLevel::class, 'job_position_level_id', 'id');
    }

    public function BossJob()
    {
        return $this->belongsTo(JobPosition::class, 'job_position_boss_id', 'id');
    }

    public function jobs()
    {
        return $this->hasMany(JobPosition::class, 'job_position_boss_id', 'id');
    }

    public function employees() {
        return $this->hasMany(Employee::class, 'job_position_id','id');
    }

    public function deleted_reason() {
        return $this->morphMany(DeletedReason::class, 'deleted_reason');
    }

    public function getStructureNames(){
        $names = "";
        // $names .= $this->getAreaName(); No hay areas por el momento
        $names .= $this->getDepartmentName();
        $names .= " / ";
        $names .= $this->getDirectionName();
        return $names;
    }

    public function getAreaName(){
        return $this->area?$this->area->name:'';
    }

    public function getDepartmentName(){
        return ($this->area && $this->area->department)?$this->area->department->name:'';
    }

    public function getDirectionName(){
        return ($this->area && $this->area->department && $this->area->department->direction)?$this->area->department->direction->name:'';
    }

    public function Jobtipobienes()
    {
        return $this->hasMany('App\Models\jobPositionsBienes', 'id_job_positions', 'id')->where('estatus',1);
    }

}

resources/views/jobPosition/beneficio.blade.php
@extends('layouts.app')
@section('content')

	<div class="col-sm-12 col-md-12 col-lg-12">
		<div class="container">
            @if(is_null($beneficio))
                <h4><center>ALGO SALIO MAL, INTENTA MAS TARDE</center></h4>
                <br>
                <h6><center>Su usuario no cuenta con beneficios</center></h6>
                <br>
            @else
                <div class="banner-gen text-center">
                    <img class="pos-img" src="{{ asset("img/beneficios/$beneficio.png") }}">
                </div>
            @endif
		</div>
	</div>

@endsection

resources/views/jobPosition/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
	<div class="flash-message" id="mensaje">
		@foreach (['danger', 'warning', 'success', 'info'] as $msg)
			@if(Session::has('alert-'.$msg))
				<p class="alert alert-{{ $msg }}">{!! Session::get('alert-'.$msg) !!} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
			@endif
		@endforeach
	</div>

	<a class="btn btn-info" href="{{ url('jobPosition') }}">Regresar</a>
	<h3 class="strong_blue">PUESTOS</h3>
	<hr>	

	<form action="{{ url('jobPosition') }}" method="POST" enctype="multipart/form-data">
		@csrf

		<div class="row mb-5">
			<div class="col-md-4 offset-md-8">
				<label for="job_position_boss_id">Puesto Jefe:</label>
				<select name="job_position_boss_id" id="job_position_boss_id" class="form-control">
					<option value="" selected>Sin Puesto Jefe</option>
					@foreach($jobs as $job)
						<option value="{{$job->id}}">{{$job->name}}</option>
					@endforeach
				</select>
			</div>
		</div>

		<div class="row">
			<div class="col-4">
				<label for="name" class="requerido">Nombre:</label>
				<input type="text" name="name" id="name" class="form-control" value="{{ old('name') }}">
				<span class="text-danger"><strong>{{ $errors->first('name') }}</strong></span>
			</div>
			<div class="col-4">
				<label for="file">Archivo:</label>
				<input type="file" name="file" id="file">
				<span class="text-danger"><strong>{{ $errors->first('file') }}</strong></span>
			</div>
			<div class="col-4">
				<label for="benefits">Beneficios:</label>
				<select name="benefits" id="benefits" class="form-control">
					<option value="" selected hidden disabled>Selecciona un beneficio</option>
					<option value="A" {{ old('benefits') == 'A' ? 'selected' : '' }}>A</option>
					<option value="B" {{ old('benefits') == 'B' ? 'selected' : '' }}>B</option>
					{{-- <option value="C" {{ old('benefits') == 'C' ? 'selected' : '' }}>C</option> --}}
				</select>
			</div>
			{{-- <div class="col-4">
				<label for="benefits">Beneficios:</label>
				<input type="file" name="benefits" id="benefits">
				<span class="text-danger"><strong>{{ $errors->first('benefits') }}</strong></span>
			</div> --}}
		</div>
		<div class="row mt-3">
			<div class="col-6">
				<label for="knowledge">Conocimientos:</label>
				<textarea name="knowledge" id="knowledge" cols="15" rows="5" class="form-control" style="resize: none;">{{ old('knowledge') }}</textarea>
			</div>
			<div class="col-6">
				<label for="experience">Funciones:</label>
				<textarea name="experience" id="experience" cols="15" rows="5" class="form-control" style="resize: none;">{{ old('experience') }}</textarea>
			</div>
		</div>
		<div class="row mt-3">
			<div class="col-6">
				<label for="comments">Objetivos:</label>
				<textarea name="comments" id="comments" cols="15" rows="5" class="form-control" style="resize: none;">{{ old('comments') }}</textarea>
			</div>
			<div class="col-6">
				<label for="description">Habilidades Requeridas:</label>
				<textarea name="description" id="description" cols="15" rows="5" class="form-control" style="resize: none;">{{ old('description') }}</textarea>
			</div>
		</div>

		<div class="row mt-4">
			<div class="col-12">
				<h4 class="font-weight-bold text-danger">Tipo de Bienes Disponibles para el puesto</h4>
				<hr style="border: 1px solid #000000;">
			</div>
		</div>
		<div class="form-row">
			@foreach ($TipoBienes as $TipoBiene)

				<div class="form-check col-md-3 form-check-inline d-flex justify-content-between align-items-center bg-check py-2 mb-4 mt-2 mb-md-0">
					<label class="form-check-label" for="{{ $TipoBiene->nombre }}">{{ $TipoBiene->nombre }}</label>
					<input class="form-check-input" type="checkbox" name="TipoBiene[{{ $TipoBiene->id }}]" id="{{ $TipoBiene->nombre }}" value="{{ $TipoBiene->id }}">
				</div>

			@endforeach
		</div>

		<div class="row mt-3">
			<button type="submit" class="btn btn-success mr-3">Guardar</button>
			<a class="btn btn-danger" href="{{ url('jobPosition') }}">Cancelar</a>
		</div>
	</form>

</div>
@endsection

resources/views/jobPosition/edit.blade.php
@extends('layouts.app')
@section('content')

<div class="container-fluid">
	<div class="flash-message" id="mensaje">
		@foreach (['danger', 'warning', 'success', 'info'] as $msg)
			@if(Session::has('alert-'.$msg))
				<p class="alert alert-{{ $msg }}">{!! Session::get('alert-'.$msg) !!} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
			@endif
		@endforeach
	</div>

	<a class="btn btn-info" href="{{ url('jobPosition') }}">Regresar</a>
	<h3 class="strong_blue">EDITA PUESTO</h3>
	<hr>

	<form action="{{ route('jobPosition.update', $job->id) }}" method="POST" enctype="multipart/form-data">
		@csrf
		@method('PUT')

		<div class="row mb-5">
			<div class="col-md-4 offset-md-8">
				<label for="job_position_boss_id">Puesto Jefe:</label>
				<select name="job_position_boss_id" id="job_position_boss_id" class="form-control">
					
					<option value="" {{ ($job->job_position_boss_id=='') ? 'selected' : null }}>Sin Puesto Jefe</option>

					@foreach($jobs as $jobP)

					   <option value="{{ $jobP->id }}" {{ ($jobP->id==$job->job_position_boss_id) ? 'selected' : null }}> {{$jobP->name}}</option>

					@endforeach

				</select>
			</div>
		</div>

		<div class="row">
			<div class="col-4">
				<label for="name" class="requerido">Nombre:</label>
				<input type="text" name="name" id="name" class="form-control" value="{{ $job->name }}">
				<span class="text-danger"><strong>{{ $errors->first('name') }}</strong></span>
			</div>
			<div class="col-5">
				<label for="file">Archivo:</label>
				<div class="row">
					<div class="col-3">
						@if (!is_null($job->file))
							<a class="btn btn-outline-secondary" href="{{ asset('puestos/'. $job->file) }}" target="_blank">
								<i class="fa fa-file-alt"></i> VER
							</a>
						@else
							<label for="" class="form-control">...</label>
						@endif
					</div>
					<div class="col-9">
						<input type="file" name="file" id="file">
						<span class="text-danger"><strong>{{ $errors->first('file') }}</strong></span>
					</div>
				</div>
			</div>

			{{-- <div class="col-4">
				<label for="file">Beneficios:</label>
				<div class="row">
					<div class="col-3">
						@if (!is_null($job->benefits))
							<a class="btn btn-outline-secondary" href="{{ asset('puestos/'. $job->benefits) }}" target="_blank">
								<i class="fa fa-file-alt"></i> VER
							</a>
						@else
							<label for="" class="form-control">Sin archivo a mostrar</label>
						@endif
					</div>
					<div class="col-9">
						<input type="file" name="benefits" id="benefits">
						<span class="text-danger"><strong>{{ $errors->first('benefits') }}</strong></span>
					</div>
				</div>
			</div> --}}
			
			<div class="col-3">
				<label for="benefits">Beneficios:</label>
				<select name="benefits" id="benefits" class="form-control">
					<option value="" {{ is_null($job->benefits) ? 'hidden selected disabled' : '' }}>Selecciona un beneficio</option>
					<option value="A" {{ $job->benefits == 'A' ? 'selected' : '' }}>A</option>
					<option value="B" {{ $job->benefits == 'B' ? 'selected' : '' }}>B</option>
					{{-- <option value="C" {{ $job->benefits == 'C' ? 'selected' : '' }}>C</option> --}}
				</select>
			</div>
		</div>
		<div class="row mt-3">
			<div class="col-6">
				<label for="knowledge">Conocimientos:</label>
				<textarea name="knowledge" id="knowledge" cols="15" rows="5" class="form-control" style="resize: none;">{{ $job->knowledge }}</textarea>
			</div>
			<div class="col-6">
				<label for="experience">Funciones:</label>
				<textarea name="experience" id="experience" cols="15" rows="5" class="form-control" style="resize: none;">{{ $job->experience }}</textarea>
			</div>
		</div>
		
		<div class="row mt-3">

			<div class="col-6">
				<label for="comments">Objetivos:</label>
				<textarea name="comments" id="comments" cols="15" rows="5" class="form-control" style="resize: none;">{{ $job->comments }}</textarea>
			</div>

			<div class="col-6">
				<label for="description">Habilidades Requeridas:</label>
				<textarea name="description" id="description" cols="15" rows="5" class="form-control" style="resize: none;">{{ $job->description }}</textarea>
			</div>

		</div>

		<div class="row mt-4">
			<div class="col-12">
				<h4 class="font-weight-bold text-danger">Tipo de Bienes Disponibles para el puesto</h4>
				<hr style="border: 1px solid #000000;">
			</div>
		</div>
		<div class="form-row">

			@foreach ($TipoBienes as $TipoBiene)
				
				<div class="form-check col-md-3 form-check-inline d-flex justify-content-between align-items-center bg-check py-2 mb-4 mt-2 mb-md-0">

					<label class="form-check-label" for="{{ $TipoBiene->nombre }}">{{ $TipoBiene->nombre }}</label>
					<input class="form-check-input" type="checkbox" name="TipoBiene[]" id="{{ $TipoBiene->nombre }}" value="{{ $TipoBiene->id }}"  {{ count($TipoBiene->jobpositionsbienes) > 0 ? 'checked' : '' }} >

				</div>
									
			@endforeach
			
		</div>

		<div class="row mt-3">
			<button type="submit" class="btn btn-success mr-3">Actualizar</button>
			<a class="btn btn-info" href="{{ url('jobPosition') }}">Regresar</a>
		</div>
	</form>

</div>
@endsection

resources/views/jobPosition/index.blade.php
@extends('layouts.app')
@section('content')

<div class="container-fluid">
	<div class="flash-message" id="mensaje">
		@foreach (['danger', 'warning', 'success', 'info'] as $msg)
			@if(Session::has('alert-'.$msg))
				<p class="alert alert-{{ $msg }}">{!! Session::get('alert-'.$msg) !!} <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a></p>
			@endif
		@endforeach
	</div>
	
	<h3>PUESTOS</h3>
	<hr>
	<div class="row">
		<div class="col-md-12 pull-right" style="text-align: right;">
			<a class="btn btn-small btn-info" href="{{ url('jobPosition/create') }}">Nuevo</a>
		</div>
	</div>
	<br>
	<table id="tablejob" class="table table-striped table-bottom-border">
		<thead>
			<tr>
				<td>Folio</td>
				<td>Puesto</td>
				<td>Puesto Jefe</td>
				<td>Descripción</td>
				<td>Beneficios</td>
				<td>Acciones</td>
			</tr>
		</thead>
		<tbody>
			@foreach($jobs as $job)
				<tr class="soft_blue_background">
					<td>{{ $job->id }}</td>
					<td>{{ $job->name }}</td>
					<td>
						@if($job->job_position_boss_id == '')
							Sin Puesto Jefe
						@else
							{{ $job->BossJob->name }}
						@endif

					</td>
					<td>{{ ($job->description?$job->description:'N/A') }}</td>
					<td>{{ $job->benefits }}</td>
					<td>
						<form action="{{ route('jobPosition.destroy', $job->id) }}" method="POST">
							@csrf
							@method('DELETE')
							<button type="submit" class="btn btn-danger"><span class="fa fa-trash-alt"></span></button>
						</form>
						<a class="btn btn-success" href="{{ url('jobPosition/' . $job->id) }}"><span class="fa fa-eye"></span></a>
						<a class="btn btn-info" href="{{ url('jobPosition/' . $job->id . '/edit') }}"><span class="fa fa-pen"></span></a>
					</td>
				</tr>
			@endforeach
		</tbody>
	</table>
</div>
@endsection
	
@section('scripts')
	<script type="text/javascript">
	$(document).ready( function () {
		$('#tablejob').DataTable({
			"language": {
				"sProcessing":     "Procesando...",
				"sLengthMenu":     "Mostrar _MENU_ registros",
				"sZeroRecords":    "No se encontraron resultados",
				"sEmptyTable":     "Ningún dato disponible en esta tabla",
				"sInfo":           "Mostrando registros del _START_ al _END_ <br>de un total de _TOTAL_ registros",
				"sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
				"sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
				"sInfoPostFix":    "",
				"sSearch":         "Buscar:",
				"sUrl":            "",
				"sInfoThousands":  ",",
				"sLoadingRecords": "Cargando...",
				"oPaginate": {
					"sFirst":    "Primero",
					"sLast":     "Último",
					"sNext":     '<span class="fa fa-arrow-right" aria-hidden="true"></span>',
					"sPrevious": '<span class="fa fa-arrow-left" aria-hidden="true"></span>',
				},
				"oAria": {
					"sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
					"sSortDescending": ": Activar para ordenar la columna de manera descendente"
				}
			}
		});
	});
	</script>
@endsection